model:
  num_classes: 3
  pretrained: true

training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  momentum: 0.85
  weight_decay: 1e-5

data:
  root: /path/to/dataset
  transform:
    resize: [256, 256]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
